import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const pluginRoot = new URL('../', import.meta.url);

test('appearance registers durable settings, a sidebar page, and completed-turn layouts', async () => {
  const [pkg, patch, host, client] = await Promise.all([
    readFile(new URL('package.json', pluginRoot), 'utf8'),
    readFile(new URL('cordis.patch.yml', pluginRoot), 'utf8'),
    readFile(new URL('src/index.ts', pluginRoot), 'utf8'),
    readFile(new URL('src/client.tsx', pluginRoot), 'utf8'),
  ]);
  assert.equal(JSON.parse(pkg).name, '@dfy-plugins/dsh-appearance');
  assert.match(patch, /id: appearance\r?\n\s+name: '@dfy-plugins\/dsh-appearance'/);
  assert.match(host, /'dsh-appearance' as SettingsNamespace/);
  assert.match(client, /name: 'settings\.section'/);
  assert.match(client, /id: 'appearance'/);
  assert.match(client, /label: '外观'/);
  assert.match(client, /installCompletedTurnLayouts/);
  assert.match(client, /\[data-turn-tail\]/);
  assert.match(client, /MutationObserver/);
  assert.doesNotMatch(client, /slots\.inject\('conversation\.chat\.turnTail'/);
  assert.match(client, /data-chat-flow-kind/);
  assert.match(client, /data-dsh-appearance-process/);
  assert.match(client, /\[data-composer-card\] \[data-input-scroll\]/);
  assert.match(client, /:is\(textarea, \[data-input-backdrop\], \[data-input-mirror\]\)/);
  assert.match(client, /font-size: var\(--dsh-appearance-chat-font-size\) !important/);
  assert.match(client, /planCompletedProcessSegments/);
  assert.match(client, /processRows\[0\] \?\? outputRow/);
  assert.match(client, /dsh-appearance-process-chevron/);
  assert.match(client, /Exact vector used by DSH's Think disclosure/);
  assert.match(client, /M11\.8486 5\.5L11\.4238 5\.92383/);
  assert.doesNotMatch(client, /dsh-appearance-process-icon/);
  assert.match(client, /每段回复前收起过程/);
  assert.match(client, /对话字号/);
  assert.match(client, /回复行距/);
  assert.match(client, /过程行距/);
  assert.match(client, /const TYPOGRAPHY_SAVE_DEBOUNCE_MS = 250/);
  assert.match(client, /window\.setTimeout\(commit, TYPOGRAPHY_SAVE_DEBOUNCE_MS\)/);
  assert.match(client, /fontSizeSave\.schedule\(value\)/);
  assert.match(client, /lineHeightSave\.schedule\(value\)/);
  assert.match(client, /processLineHeightSave\.schedule\(value\)/);
  assert.match(client, /onPointerUp=\{fontSizeSave\.flush\}/);
  assert.match(client, /onPointerUp=\{lineHeightSave\.flush\}/);
  assert.match(client, /onPointerUp=\{processLineHeightSave\.flush\}/);
  assert.match(client, /\[data-chat-flow-kind='context'\] \[data-disclosure-row\]/);
  assert.match(client, /\[data-chat-flow-kind='tool-call'\] \[data-tool\] > \[role='button'\]/);
  assert.match(client, /min-height: var\(--dsh-appearance-process-line-height\) !important/);
  assert.match(client, /min-height: var\(--dsh-appearance-process-line-height, 20px\)/);
  assert.doesNotMatch(client, /--dsh-appearance-process-line-height[^;\n]*\+\s*[46]px/);
  assert.match(client, /assistant-step'\] > div > div > :not\(\[data-variant='think'\]\)/);
  assert.match(client, /:is\(p, li, blockquote, pre, code, table, td, th\):not\(\[data-variant='think'\] \*\)/);
  assert.match(client, /data-chat-flow-kind='user'/);
  assert.match(client, /data-chat-flow-kind='steering'/);
  assert.match(client, /dsh-media-user-bubble/);
  assert.match(client, /data-time-hover-root/);
  assert.match(client, /data-actions-reveal/);
  assert.match(client, /\[class\*='_bubble'\]/);
  assert.match(client, /Math\.max\(13, fontSize - 2\)/);
  assert.match(client, /Math\.round\(fontSize \* lineHeightRatio\)/);
  assert.match(client, /Math\.round\(processSize \* processLineHeightRatio\)/);
  assert.match(client, /save\('processLineHeightRatio', DEFAULT_PROCESS_LINE_HEIGHT_RATIO\)/);
  assert.match(client, /\.dsh-appearance-reset \{ margin-top: 16px; \}/);
  assert.match(client, /className="dsh-appearance-process-toggle dsh-appearance-reset"/);
  assert.match(client, /\[data-tool="dfy_vision_analyze"\]/);
  assert.match(client, /\[data-dsh-visualization-output\], \[data-dsh-image-output\]/);
  assert.match(client, /const ARTIFACT_CONTENT = '\[data-dsh-artifact-content\]'/);
  assert.match(client, /installArtifactPromotion/);
  assert.match(client, /const promotions = new Map<string, ArtifactPromotion>\(\)/);
  assert.match(client, /current\.host\.isConnected/);
  assert.match(client, /sameElements\(current\.artifactRows, artifactRows\)\) return/);
  assert.match(client, /if \(desiredPromotions\.has\(marker\)\) continue/);
  assert.match(client, /outputRow\.after\(host\)/);
  assert.match(client, /artifactIndices/);
  assert.match(client, /collapseProcess/);
  assert.match(client, /const OFFICIAL_CHAT_SETTINGS_NAMESPACE = 'ui-chat'/);
  assert.match(client, /installOfficialTranscriptCompatibility/);
  assert.match(client, /officialScope\.set\('transcriptView', 'normal'\)/);
  assert.match(client, /appearanceScope\.subscribe\(reconcile\)/);
  assert.match(client, /processFoldingActivated/);
  assert.match(client, /customProcessFoldingEnabled/);
  assert.match(client, /officialSnapshot\.status !== 'loading'/);
  assert.match(client, /officialChatScope\.subscribe\(scheduleRefresh\)/);
  assert.match(client, /ctx\.get\?\.\('desktopContextMenu'\)/);
  assert.match(client, /ctx\.inject\(\['desktopContextMenu'\]/);
  assert.match(client, /id: 'appearance\.open-file'/);
  assert.match(client, /label: '打开文件'/);
  assert.match(client, /linkURL: \(context\) => visualizationLinkForFile/);
  assert.match(client, /id: 'appearance\.reveal-file'/);
  assert.match(client, /在访达中显示/);
  assert.match(client, /在资源管理器中显示/);
  assert.match(client, /\/api\/dsh-desktop\/shell\/reveal/);
  assert.match(client, /id: 'appearance\.open-workspace-folder'/);
  assert.match(client, /label: '打开文件夹'/);
  assert.match(client, /workspaces\.openPath\(path\)/);
  assert.match(client, /data-produced-files-row/);
  assert.match(client, /data-dsh-artifact-url/);
});
