import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import test from 'node:test';

const pluginRoot = new URL('../', import.meta.url);

test('vision separates runtime names from globally registered tool names', async () => {
  const [pkg, patch, host, client] = await Promise.all([
    readFile(new URL('package.json', pluginRoot), 'utf8'),
    readFile(new URL('cordis.patch.yml', pluginRoot), 'utf8'),
    readFile(new URL('src/index.ts', pluginRoot), 'utf8'),
    readFile(new URL('src/client.tsx', pluginRoot), 'utf8'),
  ]);

  assert.equal(JSON.parse(pkg).name, '@dfy-plugins/dsh-vision');
  assert.match(patch, /id: vision\r?\n\s+name: '@dfy-plugins\/dsh-vision'/);
  assert.match(host, /export const name = 'vision'/);
  assert.match(host, /'dsh-vision' as SettingsNamespace/);
  assert.match(host, /const API_PATH = '\/api\/dsh-vision\/routes'/);
  assert.match(host, /const RESOURCE_API_PATH = '\/api\/dsh-vision\/resource'/);
  assert.match(host, /req\.method === 'POST'/);
  assert.match(host, /await readRequestBytes\(req, byteCap\)/);
  assert.match(host, /imageRef: encodeImageRef\(ref\)/);
  assert.match(host, /presentationMeta:/);
  assert.match(host, /presentResult:/);
  assert.match(host, /attachments\.map\(\(attachment\) => createOfficialImageBlock\(attachment\)\)/);
  assert.match(host, /ctx\.attachments\.readImage\(decodeImageRef\(token\)\)/);
  assert.match(host, /decodeSessionImageRef/);
  assert.match(host, /readSessionImage/);
  assert.match(host, /sessionPersistence/);
  assert.match(host, /const ref = await ctx\.attachments\.saveImage/);
  assert.match(host, /resource_ref/);
  assert.match(host, /image_refs: \{/);
  assert.match(host, /file_paths: \{/);
  assert.match(host, /resource_refs: \{/);
  assert.match(host, /analyzeImages/);
  assert.match(host, /maxImagesPerMessage/);
  assert.match(host, /images\.map\(\(image\) => \(\{ type: 'image' as const/);
  assert.match(host, /getProcessResourceRegistry\(\)\.resolve/);
  assert.match(host, /const TOOL_NAME = 'dfy_vision_analyze'/);
  assert.match(host, /const SKILL_NAME = 'dfy-vision'/);
  assert.match(host, /description: VISION_TOOL_DESCRIPTION/);
  assert.match(host, /reasoningEffort: ReasoningEffortId\(config\.reasoningEffort\)/);
  assert.match(host, /reasoning: \{/);
  assert.match(host, /title: 'DFY VISION ANALYZE'/);
  assert.match(host, /invocation: \{ modelInvocable: true, userInvocable: true \}/);
  assert.match(host, /collect all relevant image_ref values into one image_refs array/);
  assert.match(host, /ctx\.inject\(\['mediaBlocks'\]/);
  const refresh = host.slice(host.indexOf('const refresh = async'), host.indexOf('// Keep bundle order irrelevant'));
  assert.match(refresh, /ensureFeatures\(\);[\s\S]*await ctx\.llm\.resolveModelInfo/);
  assert.match(client, /namespace: 'dsh-vision'/);
  assert.match(client, /key: 'dfy_vision_analyze'/);
  assert.match(client, />思考等级</);
  assert.match(client, /跟随模型默认/);
  assert.match(client, />DFY VISION ANALYZE</);
  assert.match(client, /已查看 \$\{String\(images\.length\)\} 张图片/);
  assert.match(client, /正在查看 \$\{String\(requestedImages\)\} 张图片/);
  assert.match(client, /'正在查看图片'/);
  assert.match(client, /function requestedImageCount\(/);
  assert.match(client, /function requestedImageAttachments\(/);
  assert.match(client, /function decodeImageRefForPreview\(/);
  assert.match(client, /const images = settledImages\.length > 0 \? settledImages : pendingImages/);
  assert.match(client, /const attachmentKey = encodeImageRef\(attachment\)/);
  assert.match(client, /\['image_ref', 'image_refs'\]/);
  assert.doesNotMatch(client, /function visionQuestion\(/);
  assert.doesNotMatch(client, /已查看 1 张图片 ·/);
  assert.match(client, /VisionImagePreview/);
  assert.match(client, /function resultImages\(/);
  assert.match(client, /function toolInput\(/);
  assert.match(client, /className="dsh-vision-tool-previews"/);
  assert.match(client, /images\.map\(\(image\) =>/);
  assert.match(client, /const \[imageOpen, setImageOpen\] = React\.useState\(false\)/);
  assert.match(client, /activeImageKeyRef\.current = imageKey;\s+setImageOpen\(false\)/);
  assert.doesNotMatch(client, /setImageOpen\(true\)/);
  assert.match(client, /dsh-vision-tool-chevron/);
  assert.match(client, /IconChevronDownOutline14 className="dsh-vision-tool-chevron"/);
  assert.match(client, /DFY VISION ANALYZE，\$\{detailsExpanded \? '收起参数' : '展开参数'\}/);
  assert.match(client, /setDetailsOpen\(\(value\) => !value\)/);
  assert.match(client, /className="dsh-vision-tool-summary-toggle"/);
  assert.match(client, /\.dsh-vision-tool-row \{[^}]*min-height: 1lh/);
  assert.match(client, /\.dsh-vision-tool-inspect-target \{[^}]*min-height: 1lh; flex: none/);
  assert.match(client, /\.dsh-vision-tool-summary-toggle \{[^}]*min-height: 1lh; flex: 0 1 auto/);
  assert.match(client, /flex: 0 1 auto/);
  assert.match(client, /text-align: left/);
  assert.match(client, /flex-flow: row wrap/);
  assert.match(client, /object-fit: cover/);
  assert.match(client, /object-position: center/);
  assert.match(client, /background: transparent/);
  assert.match(client, /width: clamp\(84px, 12vw, 112px\)/);
  assert.match(client, /aria-expanded=\{imageExpanded\}/);
  assert.match(client, /dsh-vision-tool-io-card/);
  assert.match(client, />IN</);
  assert.match(client, />OUT</);
  assert.doesNotMatch(client, /IconInspectOutline12/);
  assert.doesNotMatch(client, />查看参数</);
  assert.doesNotMatch(client, /inspect-target:hover/);
  assert.match(client, /\/api\/dsh-vision\/resource/);
  assert.match(client, /ctx\.effect\(installStyles, 'dsh-vision: client styles'\)/);
  assert.match(client, /existing\.replaceWith\(tag\)/);
  assert.doesNotMatch(client, /<style>\{STYLES\}<\/style>/);
  assert.match(client, /\.dsh-vision-card/);
});
